

EXTERN_C_START

typedef struct _QUEUE_CONTEXT {

    ULONG PrivateDeviceData;

} QUEUE_CONTEXT, *PQUEUE_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(QUEUE_CONTEXT, QueueGetContext)

NTSTATUS
ds64bQueueInitialize(
    _In_ WDFDEVICE Device
    );
EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL ds64bEvtIoDeviceControl;
EVT_WDF_IO_QUEUE_IO_STOP ds64bEvtIoStop;

EXTERN_C_END
